# Generated by Django 4.0.2 on 2022-02-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNoteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='阅读链接')),
            ],
            options={
                'verbose_name': '阅读笔记',
                'verbose_name_plural': '阅读笔记',
                'db_table': 'read_note_table',
            },
        ),
    ]
