# Generated by Django 4.0.2 on 2022-02-22 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnotemodel',
            name='edit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='readnotemodel',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
    ]
