# Generated by Django 4.0.2 on 2022-02-22 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocumentModel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='正文点击链接查看', null=True, verbose_name='正文')),
                ('link', models.CharField(max_length=512, verbose_name='链接')),
                ('publish_time', models.DateField(verbose_name='发表时间')),
                ('units_concerned', models.CharField(max_length=512, verbose_name='有关单位')),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后编辑时间')),
                ('is_alter', models.BooleanField(default=True, verbose_name='锁定')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交人员')),
            ],
            options={
                'verbose_name': '政策文件表',
                'verbose_name_plural': '政策文件表',
                'db_table': 'policy_document_table',
            },
        ),
        migrations.CreateModel(
            name='IndustryDevelopmentModel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('industry_category', models.CharField(choices=[('FFAHF', '农、林、牧、渔业'), ('MINING', '采矿业'), ('MANUFACTURING_INDUSTRY', '制造业'), ('ELECTRICITY_HEAT_GAS_WATER', '电力、热力、燃气及水生产和供应业'), ('CONSTRUCTION_INDUSTRY', '建筑业'), ('WHOLESALE_RETAIL', '批发和零售业'), ('TRANSPORTATION_WAREHOUSING_POSTAL_SERVICES', '交通运输、仓储和邮政业'), ('ACCOMMODATION_CATERING', '住宿和餐饮业'), ('IT', '信息传输、软件和信息技术服务业'), ('FINANCIAL_SECTOR', '金融业'), ('REAL_ESTATE_INDUSTRY', '房地产业'), ('LEASING_BUSINESS_SERVICES', '租赁和商务服务业'), ('SCIENTIFIC_RESEARCH_TECHNOLOGY_SERVICES', '科学研究和技术服务业'), ('WCEPFM', '水利、环境和公共设施管理业'), ('RSROS', '居民服务、修理和其他服务业'), ('EDUCATION', '教育'), ('HEALTH_SOCIAL_WORK', '卫生和社会工作'), ('CULTURE_SPORTS_ENTERTAINMENT', '文化、体育和娱乐业'), ('PASSSO', '公共管理、社会保障和社会组织'), ('INTERNATIONAL_ORGANIZATION', '国际组织')], default='IT', max_length=256, verbose_name='行业类型')),
                ('file_link', models.FileField(upload_to='industry_development/%Y/%m/%d', verbose_name='文件链接')),
                ('brief_introduction', models.CharField(max_length=512, verbose_name='简介')),
                ('units_concerned', models.CharField(max_length=512, verbose_name='有关单位')),
                ('publish_time', models.DateField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('edit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后编辑时间')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交人员')),
            ],
            options={
                'verbose_name': '行业发展报告',
                'verbose_name_plural': '行业发展报告',
                'db_table': 'industry_development_table',
            },
        ),
    ]
